#!/usr/bin/env python3
"""
Audiobook Factory - Multi-Gate Independent Verification Auditor.
Backward-compatible facade forwarding to audiobook_factory.gates.
"""

from __future__ import annotations
import subprocess

from audiobook_factory.gates import (
    GateAuditError,
    AuditResult,
    audit_gate0_translation,
    audit_gate1_roster,
    _audit_profanity_agent,
    _audit_combat_agent,
    _audit_intimacy_agent,
    audit_gate1_anticensorship_agent,
    audit_gate2_script,
    audit_gate2_screenplay_tags,
    audit_gate2_5_dramatic_fidelity,
    audit_gate2_8_performance_fidelity,
    audit_gate3_scenes,
    audit_gate3_5_acoustic_feasibility,
    audit_gate4_ledger,
    audit_gate5_master,
    audit_gate5_2_spectral_masking,
    audit_gate5_3_stereo_phase,
    audit_gate6a_voice_continuity,
    audit_gate6b_loudness_continuity,
    audit_gate6c_toc_integrity,
    audit_gate6c_toc_monotonicity,
    audit_gate6d_packaging_specs,
    audit_chapter_gates,
    audit_book_master,
    BaseLLMJudge,
    LLMTranslationJudge,
    LLMScreenplayAuditor,
    LLMDramaticCritic,
    LLMPerceptualPerformanceJudge,
    LLMSoundDesignCritic,
    TranslationFidelityVerdict,
    DialogueAttributionVerdict,
    DramaticArcVerdict,
    VocalActingVerdict,
    SoundDesignAtmosphereVerdict,
)

__all__ = [
    "GateAuditError",
    "AuditResult",
    "audit_gate0_translation",
    "audit_gate1_roster",
    "_audit_profanity_agent",
    "_audit_combat_agent",
    "_audit_intimacy_agent",
    "audit_gate1_anticensorship_agent",
    "audit_gate2_script",
    "audit_gate2_screenplay_tags",
    "audit_gate2_5_dramatic_fidelity",
    "audit_gate2_8_performance_fidelity",
    "audit_gate3_scenes",
    "audit_gate3_5_acoustic_feasibility",
    "audit_gate4_ledger",
    "audit_gate5_master",
    "audit_gate5_2_spectral_masking",
    "audit_gate5_3_stereo_phase",
    "audit_gate6a_voice_continuity",
    "audit_gate6b_loudness_continuity",
    "audit_gate6c_toc_integrity",
    "audit_gate6c_toc_monotonicity",
    "audit_gate6d_packaging_specs",
    "audit_chapter_gates",
    "audit_book_master",
    "BaseLLMJudge",
    "LLMTranslationJudge",
    "LLMScreenplayAuditor",
    "LLMDramaticCritic",
    "LLMPerceptualPerformanceJudge",
    "LLMSoundDesignCritic",
    "TranslationFidelityVerdict",
    "DialogueAttributionVerdict",
    "DramaticArcVerdict",
    "VocalActingVerdict",
    "SoundDesignAtmosphereVerdict",
]
